#!/bin/bash

search=$1
n=2
for n in "${@:2:$#}"
do
	search="$search+$n"
done

#Download the whole page and save it into a new file called result.html
wget -q "https://ssl.smn.gob.ar/mensajes/index.php?observacion=metar&operacion=consultar&tipoEstacion=OACI&CODIGO_FIR=-1&CODIGO=${search}" -O result.html

#El primer sed sirve para separar los mensajes, porque el SMN los tira todos en una sola linea y es dificil de leer así
#el segundo grep deja solo los tags que contienen los mensajes
#el tercer grep toma solamente el intervalo [METAR, "/></td>] segun la  estructura de la pag del smn
#el ultimo sed es para eliminar del mensaje el "/></td>
cat result.html | sed -e 's!<input type="hidden" !\n!g' | grep 'name="[0-9]"' |  grep -Eo 'METAR.*"\/><\/td>' | sed 's!"\/><\/td>!!g'
#remove the file
rm result.html
